### ISSUE TITLE
Irssi crash under tmux

### ISSUE THREAD

**Issue by blacksails** [paddykontschak/irssi-notifier#12]
Hi i got your script working when not using tmux.

When i use irssi inside tmux the script seems to crash irssi.

**Comment by blacksails** [comment]
The problem lies in the combination of tmux and terminal-notifier. Solved from this issue: https://github.com/julienXX/terminal-notifier/issues/115

**Comment by hughes** [comment]
So what was the solution? None of the workarounds in the linked issue seem to help.

**Comment by hughes** [comment]
Worked for me:
`brew install reattach-to-user-namespace`

Then modify the `do_notifier` subroutine in `notifier.pl` to call `system("reattach-to-user-namespace terminal-notifier -message '$data' -title '$title' >> /dev/null 2>&1");`
