### ISSUE TITLE
No notifications or dock bouncing when using notifier.pl

### ISSUE THREAD

**Issue by carwin** [paddykontschak/irssi-notifier#2]
I just picked up Mountain Lion and decided I needed this, however, following the instructions yielded no results for me. 

My configuration sans channels and servers can be seen here:
http://pastebin.com/fyuRwkir

Would love some tips to get this up and running.

**Comment by kid-icarus** [comment]
Hey @carwin,

So just to give you some tips, I'd suggest removing the <code>notifier_channel_regex = "(drupal-springfield)";</code> from your irssi config, I was having some troubles with that one.

Secondly, I'd recommend temporarily adding this to the bottom of notifier.pl:

``` perl
do_notifier('test', 'test', 'test');
```

This should open a little notification with 'test' as the title and subject.

If that doesn't work I'd recommend running the following command from the command line:

``` bash
terminal-notifier -message 'test'
```

If this command doesn't work, the script won't either.

Lastly,
Is the script in your <code>~/.irssi/scripts/autorun</code> directory?  If not, are you making sure to run <code>/script load notifier.pl</code> after irssi loads?

Hope these tips help!  BTW, you should stop by #drupal-colorado sometime, we're a lively bunch :)

**Comment by carwin** [comment]
I stopped by #drupal-colorado and you unknowingly helped me test that everything was up and running. 

The solution to my issue was removing the channel directive and letting irssi autoload the file. Thanks!
